language: python

python:
  - "3.6"
  # - "3.7"

# env:
#   - SECRET_KEY=TopSecretKey DEBUG=True ALLOWED_HOSTS=127.0.0.1 #Configuração das variáveis de ambiente
install:
  - pip install -r requirements.txt
# before_script:
#   - echo "DEBUG=False" >> .env
script:
  - tox
  - coverage run -m pytest
  - behave
  - coverage report -m

after_success:
  coveralls
